### ISSUE TITLE
COSMOS Feature to Display Affected URLs for Patterns

### ISSUE THREAD

**Issue by code-geek** [NASA-IMPACT/sde-indexing-helper#1007]
### Description

Right now if you want to exclude 50 URLs based on a pattern, then include 2 of them, there is no way to do this. This feature will allow a user to include certain URLs that fall within a pattern. This will sit on top of existing exclude patterns. We need to add this functionality to give curators more granular control over which URLs are included or excluded.

### Implementation Considerations

- For "Include URL" toggle functionality, hit appropriate `include-pattern` and `exclude-pattern` API endpoints to store the patterns.
- Take inspiration from "Candidate URLs" page to implement a "ADD PATTERN" button in "Affected URLs" page.

### Deliverable

1. Updated Affected URLs page with an "Include URL" toggle for each URL
2. Backend API endpoint to handle the inclusion of specific URLs
4. Refresh mechanism for the Affected URLs table after inclusions are made

**Comment by Kirandawadi** [comment]
This issue has been addressed by Pull Request #1038.
Successfully merging of #1038 will close this issue.

**Comment by CarsonDavis** [comment]
The code attached to this card implements the Affected Url functionality, where you can see which urls are being affected by a particular pattern. We need to refactor this to work with the new Delta patterns, potentially pointing towards Pattern.delta_urls and Pattern.curated_urls. Since these fields are inherited by all the patterns, we can probably make our functionality extent to all pattern types, not just excludes and includes.

We will work on this in PI 25.2.
